### ISSUE TITLE
GET record

### ISSUE THREAD

**Issue by michaelachrisco** [westernmilling/knackhq-client#11]
We have a method that returns an array of records but no method to return a single record.
It would be useful in case we need to test the update method. 
`api.record('object_1', knackhq_id)`

**Comment by michaelachrisco** [comment]
This is a low priority task at the moment.

**Comment by josephbridgwaterrowe** [comment]
Granted, this will probably be used... but I'm an advocate of YAGNI.

And this comment should of probably been made on the PR :smile:

**Comment by michaelachrisco** [comment]
We can actually use the feature now to double check the changes, but I think I can add it in after all of the other branches are merged. Im fine letting it sit for a bit.
